version: '3.8'
services:
  database:
    container_name: whispering-database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db-storage:/data/db
volumes:
  db-storage:
    